# Generated by Django 4.1.13 on 2025-07-27 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unitary_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Descripción')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('public_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('system_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('expiration_date', models.DateTimeField(verbose_name='Fecha de Expiración')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('expiration_date', models.DateTimeField(verbose_name='Fecha de Expiración')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('items', models.ManyToManyField(related_name='shopping_carts', through='shoppingCart.CartItemRelation', to='shoppingCart.shoppingcartitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_carts', to='shoppingCart.user')),
            ],
        ),
        migrations.AddField(
            model_name='cartitemrelation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingCart.shoppingcartitem'),
        ),
        migrations.AddField(
            model_name='cartitemrelation',
            name='shopping_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingCart.shoppingcart'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitemrelation',
            unique_together={('shopping_cart', 'item')},
        ),
    ]
