# Generated by Django 4.1.13 on 2025-07-27 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Codigo')),
                ('numericCode', models.BigIntegerField(max_length=255, unique=True, verbose_name='Codigo Numerico')),
                ('name', models.CharField(max_length=255, verbose_name='Descripción')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('public_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('system_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('expiration_date', models.DateTimeField(verbose_name='Fecha de Expiración')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
        ),
        migrations.AlterField(
            model_name='cartitemrelation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingCart.product'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='items',
            field=models.ManyToManyField(related_name='shopping_carts', through='shoppingCart.CartItemRelation', to='shoppingCart.product'),
        ),
        migrations.DeleteModel(
            name='ShoppingCartItem',
        ),
    ]
